name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Cache node_modules and Cypress
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache Playwright
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Setup Nx Cloud
        run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="playwright"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpx playwright install --with-deps

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Setup SHA for affected runs
        uses: nrwl/nx-set-shas@v3
      - run: git branch --track main origin/main

      - name: Lint & Build examples
        run: pnpm nx affected -t lint build

      - name: Run Cypress tests for examples
        run: pnpm nx affected -t cypress:ci

      - name: Run Playwright tests for examples
        run: pnpm nx affected -t playwright
