name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Build
        run: pnpm build

      - name: Lint & Build examples
        run: pnpm nx run-many -t lint build

      - name: Run Cypress tests for examples
        run: pnpm nx run-many -t cypress:ci --parallel 1

      - name: Run Playwright tests for examples
        run: pnpm nx run-many -t playwright --parallel 1
